package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// writeWrapperFn is the indirection point that tests stub to capture output
// rather than touching the filesystem.
var writeWrapperFn = writeWrapperFile

// resolveExportDir returns <cwd>/bin — the wrapper lives alongside the
// project from which parallel-each was invoked so the user can re-run it as
// ./bin/<name>.
func resolveExportDir() string {
	cwd, err := os.Getwd()
	if err != nil {
		return "bin"
	}
	return filepath.Join(cwd, "bin")
}

// writeWrapper generates and writes a wrapper script for the given config.
func writeWrapper(path string, cfg Config) error {
	content, err := renderWrapper(cfg)
	if err != nil {
		return err
	}
	return writeWrapperFn(path, content)
}

func writeWrapperFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o755)
}

// renderWrapper builds the text of a zsh wrapper that reproduces the given
// config. The wrapper assumes `parallel-each` is on PATH and forwards extra
// arguments via "$@" so the user can override or extend at call time.
func renderWrapper(cfg Config) (string, error) {
	absFile := cfg.File
	if abs, err := filepath.Abs(cfg.File); err == nil {
		absFile = abs
	}

	var args []string
	args = append(args, fmt.Sprintf("-P %d", cfg.Parallelism))
	if cfg.AttemptTimeout > 0 {
		args = append(args, fmt.Sprintf("--attempt-timeout %s", cfg.AttemptTimeout))
	}
	if cfg.TotalTimeout > 0 {
		args = append(args, fmt.Sprintf("--total-timeout %s", cfg.TotalTimeout))
	}
	if cfg.Retries != 5 {
		args = append(args, fmt.Sprintf("--retries %d", cfg.Retries))
	}
	if cfg.Fresh {
		args = append(args, "--fresh")
	}
	if cfg.SkipUniqueCheck {
		args = append(args, "--skip-unique-txt-rows")
	}
	args = append(args, "-F "+shellSingleQuote(absFile))
	args = append(args, shellSingleQuote(cfg.Template))

	var b strings.Builder
	b.WriteString("#!/usr/bin/env zsh\n")
	fmt.Fprintf(&b, "# Generated by parallel-each on %s\n", time.Now().Format("2006-01-02"))
	b.WriteString("# Extra arguments are forwarded via \"$@\"; flags earlier in the line take\n")
	b.WriteString("# precedence unless you use -- to separate.\n")
	fmt.Fprintf(&b, "exec parallel-each \\\n    %s \\\n    \"$@\"\n",
		strings.Join(args, " \\\n    "))
	return b.String(), nil
}

// shellSingleQuote wraps s in single quotes suitable for sh/zsh, escaping
// any embedded single quotes.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
