repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: ruby-validate
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, staging, --branch, main, --branch, master]
  - repo: https://github.com/mattlqx/pre-commit-ruby
    rev: v1.3.5
    hooks:
      - id: rubocop
      - id: rspec
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks:
      - id: bundler-audit
      - id: fasterer
      - id: markdownlint
      - id: reek
  - repo: https://github.com/lietu/go-pre-commit
    rev: master
    hooks:
      - id: errcheck
      - id: go-fmt-goimports
      - id: go-test
      - id: go-vet
      - id: gofumpt
      - id: golangci-lint
      - id: golint
      - id: staticcheck
      - id: go-mod-tidy
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
