version: "2"

linters:
  enable:
    - copyloopvar
    - errorlint
    - intrange
    - misspell
    - nolintlint
    - perfsprint
    - unconvert
    - usestdlibvars
    - wastedassign
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
