# shellcheck shell=sh
# AUTO-GENERATED from theme/colors.yml — 手で編集しない。
# 変更は theme/colors.yml を編集して scripts/gen_theme_colors.sh を実行する。
# (一致検査: tests/theme/test_theme_colors.sh)
# 定数は source 先で使われる (SC2034 は誤検知)
# shellcheck disable=SC2034
THEME_CURRENT_ACCENT=202
THEME_CURRENT_ACCENT_HEX="#FF5F00"
THEME_KRAFT=180
THEME_KRAFT_HEX="#D4A27F"
THEME_ACTIVE_GREEN=46
THEME_INFO_CYAN=51
THEME_MARKER_ORANGE=208
THEME_MARKER_ORANGE_HEX="#fe8019"
THEME_QUANTITY_YELLOW=214
THEME_QUANTITY_YELLOW_HEX="#fabd2f"
THEME_COLD_GRAY=240
THEME_ZOOM_RED=160
THEME_ERROR_RED=196
THEME_ERROR_RED_HEX="#ff0000"
THEME_BLINK_MAGENTA=201
THEME_BASE_PANE_BG=234
THEME_BASE_PANE_BG_HEX="#1d2021"
THEME_BASE_BAR_BG=235
THEME_BASE_BAR_BG_HEX="#282828"
