#!/usr/bin/env bash
# go_packages_index.sh — src/ の Go package doc を検査し、src/PACKAGES.md を生成する。
set -euo pipefail
unset CDPATH
unset GOOS GOARCH

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="$ROOT_DIR/src"
OUTPUT="$SRC_DIR/PACKAGES.md"
export LC_ALL=C

fail() {
	printf '✗ %s\n' "$*" >&2
	exit 1
}

mode=generate
if [ "$#" -gt 1 ]; then
	fail '使い方: scripts/go_packages_index.sh [--check]'
fi
if [ "$#" -eq 1 ]; then
	[ "$1" = '--check' ] || fail '使い方: scripts/go_packages_index.sh [--check]'
	mode=check
fi

GO_BIN="$(command -v go || true)"
[ -n "$GO_BIN" ] || fail 'go が PATH にありません (Go package index は skip しません)'
case "$GO_BIN" in
	/*) ;;
	*) GO_BIN="$(cd "$(dirname "$GO_BIN")" && pwd)/$(basename "$GO_BIN")" ;;
esac

tmp_dir="$(mktemp -d)" || fail '一時ディレクトリを作れません'
out_tmp=''
trap 'rm -rf "$tmp_dir"; [ -z "$out_tmp" ] || rm -f "$out_tmp"' EXIT

module_list="$tmp_dir/modules"
package_dirs="$tmp_dir/package-dirs"
sorted_package_dirs="$tmp_dir/package-dirs-sorted"
expected="$tmp_dir/PACKAGES.md"
query_stderr="$tmp_dir/go-list.stderr"
: > "$module_list"
: > "$package_dirs"

for go_mod in "$SRC_DIR"/*/go.mod; do
	[ -f "$go_mod" ] || continue
	module_dir="${go_mod%/go.mod}"
	module_rel="${module_dir#"$ROOT_DIR"/}"
	printf '%s\n' "$module_rel" >> "$module_list"
done
[ -s "$module_list" ] || fail 'src/*/go.mod の module が 0 件です'

nested_modules="$(find "$SRC_DIR" -mindepth 3 -name go.mod -print | sort)" || fail 'nested module の検査に失敗しました'
if [ -n "$nested_modules" ]; then
	first_nested="$(printf '%s\n' "$nested_modules" | sed -n '1p')"
	first_nested_rel="${first_nested#"$ROOT_DIR"/}"
	fail "nested Go module は未対応です: $first_nested_rel (src/*/go.mod 直下へ移してください)"
fi

module_count=0
while IFS= read -r module_rel; do
	[ -n "$module_rel" ] || continue
	module_dir="$ROOT_DIR/$module_rel"
	module_packages="$tmp_dir/module-$module_count-packages"
	if ! (
		cd "$module_dir" || exit 1
		find . -mindepth 1 -type d \( -name vendor -o -name testdata -o -name '.*' -o -name '_*' \) -prune -o \
			\( -type f -o -type l \) -name '*.go' ! -name '*_test.go' -print |
			awk '{ sub(/\/[^\/]*$/, ""); sub(/^\.\//, ""); if ($0 == "") $0 = "."; print }' |
			sort -u |
			awk -v module="$module_rel" '{ if ($0 == ".") print module; else print module "/" $0 }'
	) > "$module_packages"; then
		fail "package directory の発見に失敗しました: $module_rel"
	fi
	module_package_count="$(wc -l < "$module_packages" | tr -d '[:space:]')"
	[ "$module_package_count" -gt 0 ] || fail "module の package が 0 件です: $module_rel"
	cat "$module_packages" >> "$package_dirs"
	module_count=$((module_count + 1))
done < "$module_list"

sort -u "$package_dirs" > "$sorted_package_dirs" || fail 'package directory の sort に失敗しました'

GO_LIST_FORMAT='{{.ImportPath}}{{printf "\x1f"}}{{.Dir}}{{printf "\x1f"}}{{.Name}}{{printf "\x1f"}}{{.Doc}}{{printf "\x1f"}}{{if .Error}}{{.Error.Err}}{{end}}'
query_go_list() {
	local package_abs="$1"
	local tags="$2"
	: > "$query_stderr"
	GO_OUTPUT=''
	GO_RC=0
	if [ -n "$tags" ]; then
		if GO_OUTPUT="$(cd "$package_abs" && GOWORK=off GOENV=off GOFLAGS='' GOTOOLCHAIN=local LC_ALL=C "$GO_BIN" list -find -e -f "$GO_LIST_FORMAT" -tags "$tags" . 2>"$query_stderr")"; then
			GO_RC=0
		else
			GO_RC=$?
		fi
	else
		if GO_OUTPUT="$(cd "$package_abs" && GOWORK=off GOENV=off GOFLAGS='' GOTOOLCHAIN=local LC_ALL=C "$GO_BIN" list -find -e -f "$GO_LIST_FORMAT" . 2>"$query_stderr")"; then
			GO_RC=0
		else
			GO_RC=$?
		fi
	fi
}

build_tags_for() {
	local package_abs="$1"
	local tags_file="$tmp_dir/build-tags"
	local source_file
	: > "$tags_file"
	for source_file in "$package_abs"/*.go; do
		[ -f "$source_file" ] || continue
		case "$source_file" in *_test.go) continue ;; esac
		if awk '
			/^\/\/go:build[[:space:]]/ {
				line = $0
				sub(/^\/\/go:build[[:space:]]+/, "", line)
				if (line ~ /!/) exit 2
				while (match(line, /[[:alnum:]_.]+/)) {
					print substr(line, RSTART, RLENGTH)
					line = substr(line, RSTART + RLENGTH)
				}
			}
		' "$source_file" >> "$tags_file"; then
			:
		else
			return "$?"
		fi
	done
	[ -s "$tags_file" ] || return 1
	sort -u "$tags_file" | awk '!seen[$0]++ { if (out != "") out = out ","; out = out $0 } END { print out }'
}

package_count=0
{
	printf "<!-- Generated by scripts/go_packages_index.sh. Recreate with \`scripts/go_packages_index.sh\`; do not edit. -->\n\n"
	printf '# Go packages\n\n'
	while IFS= read -r package_rel; do
		[ -n "$package_rel" ] || continue
		package_abs="$ROOT_DIR/$package_rel"
		for source_file in "$package_abs"/*.go; do
			[ -L "$source_file" ] || continue
			case "$source_file" in *_test.go) continue ;; esac
			if ! cat "$source_file" >/dev/null 2>&1; then
				fail "Go source symlink の参照先を読めません: $package_rel/$(basename "$source_file")"
			fi
		done
		query_go_list "$package_abs" ''
		[ "$GO_RC" -eq 0 ] || fail "go list が失敗しました: $package_rel (rc=$GO_RC) $(cat "$query_stderr")"
		[ -n "$GO_OUTPUT" ] || fail "go list が package 情報を返しませんでした: $package_rel"
		case "$GO_OUTPUT" in *$'\n'*) fail "go list が package 情報を複数行返しました: $package_rel" ;; esac
		IFS=$'\037' read -r import_path listed_dir package_name package_doc list_error <<< "$GO_OUTPUT"
		[ -n "$import_path" ] && [ -n "$listed_dir" ] \
			|| fail "go list の package 情報が不完全です: $package_rel"
		[ "$listed_dir" = "$package_abs" ] || fail "go list の directory が一致しません: $package_rel ($listed_dir)"

		tags=''
		tagged=0
		case "$list_error" in
			*'build constraints exclude all Go files'*)
				if tags="$(build_tags_for "$package_abs")"; then
					:
				else
					tag_rc=$?
					if [ "$tag_rc" -eq 2 ]; then
						fail "否定を含む //go:build 行は未対応です: $package_rel"
					fi
					fail "build tag 除外を再取得できません: $package_rel (//go:build tag がありません)"
				fi
				query_go_list "$package_abs" "$tags"
				[ "$GO_RC" -eq 0 ] || fail "build tag 付き go list が失敗しました: $package_rel (rc=$GO_RC) $(cat "$query_stderr")"
				[ -n "$GO_OUTPUT" ] || fail "build tag 付き go list が package 情報を返しませんでした: $package_rel"
				case "$GO_OUTPUT" in *$'\n'*) fail "build tag 付き go list が package 情報を複数行返しました: $package_rel" ;; esac
				IFS=$'\037' read -r import_path listed_dir package_name package_doc list_error <<< "$GO_OUTPUT"
				[ -n "$import_path" ] && [ -n "$listed_dir" ] && [ -n "$package_name" ] \
					|| fail "build tag 付き go list の package 情報が不完全です: $package_rel"
				[ "$listed_dir" = "$package_abs" ] || fail "go list の directory が一致しません: $package_rel ($listed_dir)"
				tagged=1
				;;
		esac
		[ -z "$list_error" ] || fail "go list の .Error が空ではありません: $package_rel ($list_error)"
		[ -n "$package_name" ] || fail "go list の package 情報が不完全です: $package_rel"

		raw_package_doc="$package_doc"
		nonempty_doc="$(printf '%s\n' "$raw_package_doc" | awk '{$1 = $1; print}')"
		[ -n "$nonempty_doc" ] || fail "package doc comment が空です: $package_rel"
		if [ "$package_name" != main ]; then
			doc_prefix="Package $package_name "
			case "$raw_package_doc" in
				"$doc_prefix"*) ;;
				*) fail "非 main package の doc は '$doc_prefix' で始めてください: $package_rel" ;;
			esac
		fi
		package_doc="$(printf '%s\n' "$raw_package_doc" | tr '\r\n' '  ' | awk '{$1 = $1; print}')"

		marks=''
		case "/$package_rel/" in */internal/*) marks='internal' ;; esac
		if [ "$package_name" = main ]; then
			if [ -n "$marks" ]; then marks="$marks, main"; else marks='main'; fi
		fi
		if [ "$tagged" -eq 1 ]; then
			if [ -n "$marks" ]; then marks="$marks, build tags: $tags"; else marks="build tags: $tags"; fi
		fi
		if [ -n "$marks" ]; then
			printf -- "- \`%s\` (\`%s\`) — %s (%s)\n" "$package_rel" "$import_path" "$package_doc" "$marks"
		else
			printf -- "- \`%s\` (\`%s\`) — %s\n" "$package_rel" "$import_path" "$package_doc"
		fi
		package_count=$((package_count + 1))
	done < "$sorted_package_dirs"
} > "$expected"

[ "$package_count" -gt 0 ] || fail 'package が 0 件です'

if [ "$mode" = check ]; then
	if ! cmp -s "$expected" "$OUTPUT"; then
		printf '✗ src/PACKAGES.md is stale; run scripts/go_packages_index.sh\n' >&2
		diff -u "$OUTPUT" "$expected" >&2 || true
		exit 1
	fi
	printf 'OK: Go package index を検査しました (%s modules / %s packages)\n' "$module_count" "$package_count"
else
	# 生成物は同じディレクトリの一時ファイルから rename する (書きかけの PACKAGES.md を残さない)
	out_tmp="$(mktemp "$OUTPUT.XXXXXX")" || fail 'src/PACKAGES.md の一時ファイルを作れません'
	cp "$expected" "$out_tmp"
	mv "$out_tmp" "$OUTPUT"
	out_tmp=''
	printf '✓ src/PACKAGES.md を生成しました (%s modules / %s packages)\n' "$module_count" "$package_count"
fi
