# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "docker"
  config.vm.provision :docker_compose
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y ruby-dev lv zsh vim build-essential bison
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant -c 'command curl -sSL https://rvm.io/mpapis.asc | gpg --import -'
    su - vagrant -c 'command curl -sSL https://get.rvm.io | bash -s stable'
  SHELL
end
