# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "docker"
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y ruby-dev lv zsh vim build-essential bison
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
    \\curl -sSL https://get.rvm.io | bash
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
    curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
    sudo mkdir /opt
    sudo mkdir /opt/bin
    sudo mv ~/docker-compose /opt/bin/docker-compose
    sudo chown root:root /opt/bin/docker-compose
    sudo chmod +x /opt/bin/docker-compose
    sudo mv /opt/bin/docker-compose /usr/local/bin
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
    apt-get purge nano -f
    echo "deb http://packages.treasuredata.com/2/debian/jessie/ jessie contrib" > /etc/apt/sources.list.d/treasure-data.list
    sudo apt-get update
    apt-get install -y --force-yes td-agent
  SHELL
end
